"""empty message

Revision ID: 4654718a422c
Revises: 00d9aecc988d
Create Date: 2022-12-24 04:31:28.666799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4654718a422c'
down_revision = '00d9aecc988d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('year', sa.String(length=50), nullable=False),
    sa.Column('logline', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scripts')
    # ### end Alembic commands ###
