"""empty message

Revision ID: 488d15fb3e41
Revises: e58b8a7d5052
Create Date: 2022-12-29 19:10:44.493383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488d15fb3e41'
down_revision = 'e58b8a7d5052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scriptcover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scriptcover', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
