"""empty message

Revision ID: 4b8c1163f4ea
Revises: 61c979ab9600
Create Date: 2022-12-27 21:52:10.483703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8c1163f4ea'
down_revision = '61c979ab9600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploadscript',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploadscript')
    # ### end Alembic commands ###
