"""empty message

Revision ID: 56924bbd01b3
Revises: 4654718a422c
Create Date: 2022-12-24 08:12:56.777742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56924bbd01b3'
down_revision = '4654718a422c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.drop_column('url')
        batch_op.drop_column('cover')

    # ### end Alembic commands ###
