"""empty message

Revision ID: ac8a1e556628
Revises: 4b8c1163f4ea
Create Date: 2022-12-28 11:08:29.857551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac8a1e556628'
down_revision = '4b8c1163f4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploadscript')
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=250), nullable=False))
        batch_op.create_unique_constraint(None, ['uuid'])
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', mysql.VARCHAR(length=250), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('uuid')

    op.create_table('uploadscript',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('script_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], name='uploadscript_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
