"""empty message

Revision ID: e58b8a7d5052
Revises: ac8a1e556628
Create Date: 2022-12-28 12:35:36.591009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e58b8a7d5052'
down_revision = 'ac8a1e556628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scriptcover', schema=None) as batch_op:
        batch_op.alter_column('script_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('scriptcover_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.alter_column('cover',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scripts', schema=None) as batch_op:
        batch_op.alter_column('cover',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)

    with op.batch_alter_table('scriptcover', schema=None) as batch_op:
        batch_op.create_foreign_key('scriptcover_ibfk_1', 'scripts', ['script_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('script_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
